### ISSUE TITLE
Debian 11 Bullseye support

### ISSUE THREAD

**Issue by Neustradamus** [myvesta/vesta#110]
Can you add the Debian 11 Bullseye support?

**Comment by myvesta** [comment]
As soon as release date become near.
But I promise it will be **before** release date of Deb11 :)

**Comment by didyouexpectthat** [comment]
Hi @myvesta, Debian 11 is already essentially released except the installer for new installs. Any ETA on when we'll see support for Debian 11? Thank you very much.

**Comment by myvesta** [comment]
I will try to do it in next 30 days.
Don't worry, we will be really fast about it, since we aready have building scripts.

**Comment by myvesta** [comment]
Started to working on it.
Currently building binaries for php-nginx and vesta-php.
Will see how much modifications will be needed for installer and config files.
I will post here progrees.

**Comment by myvesta** [comment]
And it is done :)
![image](https://user-images.githubusercontent.com/38690722/126041000-6531947f-5a7f-46c2-935c-496a0d78728f.png)

Feel free to test.
I tested only main functionality, but bugs on offshoots are possible.

**Comment by didyouexpectthat** [comment]
So far, so good. My plan is to migrate my production from one server to another server so I'll be migrating over the next few days and will report any issues I find. 
![image](https://user-images.githubusercontent.com/1329077/126042984-49cf54ef-ef8a-41e0-8a75-3a9ab90730a1.png)
![image](https://user-images.githubusercontent.com/1329077/126042990-7bb2e9f8-b84e-4eea-835c-2ce6117f25b0.png)

**Comment by myvesta** [comment]
@didyouexpectthat but again, keep in mind that I couldn't check everything, and that even Debian11 is not still released :)

I didn't check ClamAV, SpamAssassin, fail2ban.

Exim got big big config changes - because they depricated some stuff in configs - https://github.com/myvesta/vesta/commit/1a6785eb704322cf66fc93155939d4143c43d81f - so be careful with Exim.
@madeITBelgium solved it in his fork - I got solutions from there - but I'm not sure that I correctly implemented it - we need further checking there - aliases, forwarding, auto-reply...

On web stack i'm not expecting any problems.

I will also slowly check it in production - with future servers that I will install, but I can be "brave" because I can quickly respond if an error exists... so once again... be careful with Deb11 in next few months - don't put it on server that needs 100% stability :D

**Comment by didyouexpectthat** [comment]
:) I'm aware of the risks and can keep both sites up at the same time while I am testing. I'm checking things as I go as well to make sure it is still working as expected. So far, proftpd did not start after upgrade. In my /etc/proftpd/proftpd.conf config file, line 31 is for IdentLookup, which I commented out and was able to start proftpd.

**Comment by myvesta** [comment]
@didyouexpectthat 
yes, I put IfModule there - https://github.com/myvesta/vesta/commit/fb98936297b472d5c3740332c65854f87c7e75de
But if you did upgrade from deb10, it will not be downloaded, of course, I still didn't make upgrade walkthrough for deb10->deb11
Also, in that case, Exim needs full config replacement, as I already said.

**Comment by myvesta** [comment]
If you did upgrade from deb10, you also need https://github.com/myvesta/vesta/commit/2c91d72277d7593ac698bab5e832ca57c5aeeb91#diff-82d81c518175b443c94b03f346ed91cc1cf797d3e48378d86141f6c70997e548R1409-R1413 because of https://www.debian.org/releases/testing/amd64/release-notes/ch-information.en.html#pam-default-password

**Comment by didyouexpectthat** [comment]
Exim4 is started but these are what I see, errorwise.
```
2021-07-17 10:04:56 1m4mjV-0002rF-P4 Tainted filename for search '/etc/exim4/domains/sub.domain.com/passwd'
2021-07-17 10:04:56 1m4mjV-0002rF-P4 failed to expand condition "${if eq {${if match{$h_X-Spam-Status:}{\N^Yes\N}{yes}{no}}} {${lookup{$local_part}lsearch{/etc/exim4/domains/$domain/passwd}{yes}{no_such_user}}}}" for localuser_spam router: NULL
2021-07-17 10:04:56 1m4mjV-0002rF-P4 Tainted filename for search '/etc/exim4/domains/sub.domain.com/aliases'
```

**Comment by didyouexpectthat** [comment]
> If you did upgrade from deb10, you also need [2c91d72#diff-82d81c518175b443c94b03f346ed91cc1cf797d3e48378d86141f6c70997e548R1409-R1413](https://github.com/myvesta/vesta/commit/2c91d72277d7593ac698bab5e832ca57c5aeeb91#diff-82d81c518175b443c94b03f346ed91cc1cf797d3e48378d86141f6c70997e548R1409-R1413) because of https://www.debian.org/releases/testing/amd64/release-notes/ch-information.en.html#pam-default-password

I am reviewing the changes to the debian installer to make sure I have everything.

**Comment by myvesta** [comment]
@didyouexpectthat 
yes, that will happen without new config - https://github.com/myvesta/vesta/blob/master/install/debian/11/exim/exim4.conf.template
because it will not be downloaded if you did upgrade from deb10 to deb11

diff is here - https://github.com/myvesta/vesta/commit/1a6785eb704322cf66fc93155939d4143c43d81f

**Comment by didyouexpectthat** [comment]
During the upgrade, I did not choose any new configs because I had done that before with vestacp and it broke everything.  What is your suggestion in that case? Is there a command that can restore myvesta default templates?

**Comment by myvesta** [comment]
@didyouexpectthat currently we don't have upgrading walkthrough. nor script that will download adapted config files.
Until we make it, i'm not advice doing upgrade from deb10 to deb11, i'm recommending just fresh install for deb11, and moving backup from old to new server.

**Comment by didyouexpectthat** [comment]
No worries. I will review the diffs and let you know if I run across any other problems to document.

**Comment by Neustradamus** [comment]
Yesterday, it was the Debian 11 release date:
- https://www.debian.org/News/2021/20210814

**Comment by myvesta** [comment]
Well, we are ready :)

**Comment by Neustradamus** [comment]
@myvesta: Yes it is very good, all projects must be like it.

**Comment by Neustradamus** [comment]
There is a problem on Website:  07-Nov-2021 vs 17-Jul-2021.

https://myvestacp.com/
Latest release: 0.9.8-26-49
Latest build date: 07-Nov-2021

Changelog:
Version 0.9.8-26-49 [17-Jul-2021]
==================================================
* Support for Debian 11

On GitHub: 
- 0.9.8-26-49: 17 Jul 2021: https://github.com/myvesta/vesta/releases/tag/0.9.8-26-49

**Comment by myvesta** [comment]
@Neustradamus 
do Ctrl+F5

**Comment by Neustradamus** [comment]
You have done a change after with a new build ;)
