### ISSUE TITLE
SSL problem

### ISSUE THREAD

**Issue by 1webdomain** [myvesta/vesta#62]
### Operating System (OS/VERSION):

Debian 10.4

### VestaCP Version:

myVesta 0.9.8-26-20 Build date: 01-Jun-2020

### Installed Software (what you got with the installer):

php-fpm, apache, nginx, mysql + multi-php-install.sh

### Steps to Reproduce:

https problem with cloudflare setup @ FULL SSL

### Other Notes:

what script do you consider for this problem ?
https://github.com/myvesta/vesta/blob/master/src/deb/vesta/postinst
or
https://github.com/myvesta/vesta/blob/master/bin/v-add-web-domain-ssl
or 
https://github.com/myvesta/vesta/commit/9cdfaf483f16ab2163be987a8d0e03f7f361dd8b
THX

**Comment by 1webdomain** [comment]
sorry las link was https://github.com/myvesta/vesta/commit/9cdfaf483f16ab2163be987a8d0e03f7f361dd8b

**Comment by myvesta** [comment]
https://github.com/myvesta/vesta/commit/9cdfaf483f16ab2163be987a8d0e03f7f361dd8b will just remove depricated SSL directives in templates.
Since you has Debian10, I believe you even don't have those directives, and issue is not here.
Additionaly, that commit is from yesterday, and you have Build date: 01-Jun-2020, so that commit is not yet applied to your server.

Can you describe how problem looks like?

Did you try to turn-off Cloudflare firewall (icon of cloud) for www and @, and to generate SSL ?

**Comment by 1webdomain** [comment]
now i have Build date: 14-Jun-2020 and https seems to work well, have you changed something?

**Comment by myvesta** [comment]
Literally nothing was changed related to generating letsencrypt... 
i just removed ability for LE to be scheduled, because it can go to infinite cronjob loop... but i don't believe it's related with your issue.

**Comment by 1webdomain** [comment]
OK THX anymore
